### ISSUE TITLE
GWLB and Application Gateway

### ISSUE THREAD

**Issue by Petri-X** [adstuart/azure-gwlb-chain#1]
Hi Adam,
Just a short question, looks like the chaining with application gateway is at the moment not supported/possible, but do you know if that is even on the planning table on the future released?
The main idea is to be able to control the traffic flying in to the App GW as well.

**Comment by adstuart** [comment]
Hi Petri - I can't talk about non-public roadmap on a public forum, please talk to your Microsoft team.
